# This is the configuration used to check the rubocop source code.
# See https://github.com/bbatsov/rubocop/blob/master/config/default.yml for options

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'db/seeds/**/*.rb'
    - 'db/seeds.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'Brewfile'
  Exclude:
    - 'db/migrate/**/*.rb'
    - 'db/migrate/**/*.rb'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/fixtures/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'Guardfile'
    - 'test/test_helper.rb'

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/DotPosition:
  EnforcedStyle: trailing

Lint/UnusedBlockArgument:
  Enabled: true

Metrics/AbcSize:
  Max: 35

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'test/**/*_test.rb'

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FileName:
  Exclude:
    - 'Capfile'
    - 'Guardfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: call
  Exclude:
    - 'app/**/*.jbuilder'

Style/PredicateName:
  NamePrefixBlacklist:
    - is_
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  MinSize: 3

Style/WordArray:
  MinSize: 3

Metrics/BlockLength:
  Exclude:
    - 'app/rails_admin_models/*.rb'
    - 'app/views/**/*'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*'
    - 'test/**/*'

Bundler/OrderedGems:
  Enabled: false
